/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Matrix (https://sketchfab.com/TUONO)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-marine-dffb2975c74c4be8ac4dd991caa03032
Title: SPACE MARINE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['HELMET_POSE_8-24-20_Default_OBJ_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ']} />
          <mesh geometry={nodes['HELMET_POSE_8-24-20_Default_OBJ_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ']} />
          <mesh geometry={nodes['HELMET_POSE_8-24-20_Default_OBJ_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ']} />
          <mesh geometry={nodes['HELMET_POSE_8-24-20_Default_OBJ_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_ELBOW_POSE_8-24-20_Default_OBJ_001_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_001']} />
          <mesh geometry={nodes['L_ELBOW_POSE_8-24-20_Default_OBJ_001_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_001']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_FOREARM_POSE_8-24-20_Default_OBJ_004_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_004']} />
          <mesh geometry={nodes['L_FOREARM_POSE_8-24-20_Default_OBJ_004_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_004']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_INDEX_1_POSE_8-24-20_Default_OBJ_006_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_006']} />
          <mesh geometry={nodes['L_HAND_INDEX_1_POSE_8-24-20_Default_OBJ_006_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_006']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_INDEX_2_POSE_8-24-20_Default_OBJ_007_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_007']} />
          <mesh geometry={nodes['L_HAND_INDEX_2_POSE_8-24-20_Default_OBJ_007_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_007']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_MIDDLE_1_POSE_8-24-20_Default_OBJ_009_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_009']} />
          <mesh geometry={nodes['L_HAND_MIDDLE_1_POSE_8-24-20_Default_OBJ_009_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_009']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_MIDDLE_2_POSE_8-24-20_Default_OBJ_010_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_010']} />
          <mesh geometry={nodes['L_HAND_MIDDLE_2_POSE_8-24-20_Default_OBJ_010_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_010']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_PINKY_1_POSE_8-24-20_Default_OBJ_013_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_013']} />
          <mesh geometry={nodes['L_HAND_PINKY_1_POSE_8-24-20_Default_OBJ_013_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_013']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_PINKY_2_POSE_8-24-20_Default_OBJ_014_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_014']} />
          <mesh geometry={nodes['L_HAND_PINKY_2_POSE_8-24-20_Default_OBJ_014_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_014']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_RING_1_POSE_8-24-20_Default_OBJ_016_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_016']} />
          <mesh geometry={nodes['L_HAND_RING_1_POSE_8-24-20_Default_OBJ_016_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_016']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_RING_2_POSE_8-24-20_Default_OBJ_017_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_017']} />
          <mesh geometry={nodes['L_HAND_RING_2_POSE_8-24-20_Default_OBJ_017_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_017']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_THUMB_1_POSE_8-24-20_Default_OBJ_019_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_019']} />
          <mesh geometry={nodes['L_HAND_THUMB_1_POSE_8-24-20_Default_OBJ_019_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_019']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_THUMB_2_POSE_8-24-20_Default_OBJ_020_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_020']} />
          <mesh geometry={nodes['L_HAND_THUMB_2_POSE_8-24-20_Default_OBJ_020_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_020']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_THUMB_3_POSE_8-24-20_Default_OBJ_021_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_021']} />
          <mesh geometry={nodes['L_HAND_THUMB_3_POSE_8-24-20_Default_OBJ_021_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_021']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HIP_ARMOR_POSE_8-24-20_Default_OBJ_022_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_022']} />
          <mesh geometry={nodes['L_HIP_ARMOR_POSE_8-24-20_Default_OBJ_022_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_022']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_SHOULDER_PAD_POSE_8-24-20_Default_OBJ_028_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_028']} />
          <mesh geometry={nodes['L_SHOULDER_PAD_POSE_8-24-20_Default_OBJ_028_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_028']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_ELBOW_POSE_8-24-20_Default_OBJ_031_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_031']} />
          <mesh geometry={nodes['R_ELBOW_POSE_8-24-20_Default_OBJ_031_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_031']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_FOREARM_POSE_8-24-20_Default_OBJ_034_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_034']} />
          <mesh geometry={nodes['R_FOREARM_POSE_8-24-20_Default_OBJ_034_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_034']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_INDEX_1_POSE_8-24-20_Default_OBJ_036_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_036']} />
          <mesh geometry={nodes['R_HAND_INDEX_1_POSE_8-24-20_Default_OBJ_036_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_036']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_INDEX_2_POSE_8-24-20_Default_OBJ_037_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_037']} />
          <mesh geometry={nodes['R_HAND_INDEX_2_POSE_8-24-20_Default_OBJ_037_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_037']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_MIDDLE_1_POSE_8-24-20_Default_OBJ_039_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_039']} />
          <mesh geometry={nodes['R_HAND_MIDDLE_1_POSE_8-24-20_Default_OBJ_039_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_039']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_MIDDLE_2_POSE_8-24-20_Default_OBJ_040_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_040']} />
          <mesh geometry={nodes['R_HAND_MIDDLE_2_POSE_8-24-20_Default_OBJ_040_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_040']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_PINKY_1_POSE_8-24-20_Default_OBJ_043_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_043']} />
          <mesh geometry={nodes['R_HAND_PINKY_1_POSE_8-24-20_Default_OBJ_043_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_043']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_PINKY_2_POSE_8-24-20_Default_OBJ_044_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_044']} />
          <mesh geometry={nodes['R_HAND_PINKY_2_POSE_8-24-20_Default_OBJ_044_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_044']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_RING_1_POSE_8-24-20_Default_OBJ_046_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_046']} />
          <mesh geometry={nodes['R_HAND_RING_1_POSE_8-24-20_Default_OBJ_046_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_046']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_RING_2_POSE_8-24-20_Default_OBJ_047_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_047']} />
          <mesh geometry={nodes['R_HAND_RING_2_POSE_8-24-20_Default_OBJ_047_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_047']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_THUMB_1_POSE_8-24-20_Default_OBJ_049_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_049']} />
          <mesh geometry={nodes['R_HAND_THUMB_1_POSE_8-24-20_Default_OBJ_049_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_049']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_THUMB_2_POSE_8-24-20_Default_OBJ_050_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_050']} />
          <mesh geometry={nodes['R_HAND_THUMB_2_POSE_8-24-20_Default_OBJ_050_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_050']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_THUMB_3_POSE_8-24-20_Default_OBJ_052_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_052']} />
          <mesh geometry={nodes['R_HAND_THUMB_3_POSE_8-24-20_Default_OBJ_052_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_052']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HIP_ARMOR_POSE_8-24-20_Default_OBJ_053_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_053']} />
          <mesh geometry={nodes['R_HIP_ARMOR_POSE_8-24-20_Default_OBJ_053_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_053']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_SHOULDER_PAD_POSE_8-24-20_Default_OBJ_058_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_058']} />
          <mesh geometry={nodes['R_SHOULDER_PAD_POSE_8-24-20_Default_OBJ_058_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_058']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['TORSO_WINGED_POSE_8-24-20_Default_OBJ_061_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_061']} />
          <mesh geometry={nodes['TORSO_WINGED_POSE_8-24-20_Default_OBJ_061_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_061']} />
          <mesh geometry={nodes['TORSO_WINGED_POSE_8-24-20_Default_OBJ_061_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_061']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['WAIST_WAIST_001_POSE_8-24-20_Default_OBJ_065_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_065']} />
          <mesh geometry={nodes['WAIST_WAIST_001_POSE_8-24-20_Default_OBJ_065_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_065']} />
          <mesh geometry={nodes['WAIST_WAIST_001_POSE_8-24-20_Default_OBJ_065_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_065']} />
          <mesh geometry={nodes['WAIST_WAIST_001_POSE_8-24-20_Default_OBJ_065_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_065']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['BOLTER_POSE_8-24-20_Default_OBJ_066_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_066']} />
          <mesh geometry={nodes['BOLTER_POSE_8-24-20_Default_OBJ_066_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_066']} />
          <mesh geometry={nodes['BOLTER_POSE_8-24-20_Default_OBJ_066_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_066']} />
          <mesh geometry={nodes['BOLTER_POSE_8-24-20_Default_OBJ_066_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_066']} />
          <mesh geometry={nodes['BOLTER_POSE_8-24-20_Default_OBJ_066_0_4'].geometry} material={materials['POSE_8-24-20_Default_OBJ_066']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_051_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_051']} />
          <mesh geometry={nodes['L_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_051_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_051']} />
          <mesh geometry={nodes['L_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_051_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_051']} />
          <mesh geometry={nodes['L_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_051_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_051']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_062_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_062']} />
          <mesh geometry={nodes['R_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_062_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_062']} />
          <mesh geometry={nodes['R_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_062_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_062']} />
          <mesh geometry={nodes['R_HAND_GLOVE_MESH_001_POSE_8-24-20_Default_OBJ_062_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_062']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_4'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_5'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_6'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_7'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_8'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
          <mesh geometry={nodes['BACKPACK_BACKPACK_001_POSE_8-24-20_Default_OBJ_067_0_9'].geometry} material={materials['POSE_8-24-20_Default_OBJ_067']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_FOOT_L_FOOT_001_POSE_8-24-20_Default_OBJ_068_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_068']} />
          <mesh geometry={nodes['L_FOOT_L_FOOT_001_POSE_8-24-20_Default_OBJ_068_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_068']} />
          <mesh geometry={nodes['L_FOOT_L_FOOT_001_POSE_8-24-20_Default_OBJ_068_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_068']} />
          <mesh geometry={nodes['L_FOOT_L_FOOT_001_POSE_8-24-20_Default_OBJ_068_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_068']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['L_SHIN_001_POSE_8-24-20_Default_OBJ_070_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_070']} />
          <mesh geometry={nodes['L_SHIN_001_POSE_8-24-20_Default_OBJ_070_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_070']} />
          <mesh geometry={nodes['L_SHIN_001_POSE_8-24-20_Default_OBJ_070_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_070']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_FOOT_001_POSE_8-24-20_Default_OBJ_071_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_071']} />
          <mesh geometry={nodes['R_FOOT_001_POSE_8-24-20_Default_OBJ_071_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_071']} />
          <mesh geometry={nodes['R_FOOT_001_POSE_8-24-20_Default_OBJ_071_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_071']} />
          <mesh geometry={nodes['R_FOOT_001_POSE_8-24-20_Default_OBJ_071_0_3'].geometry} material={materials['POSE_8-24-20_Default_OBJ_071']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['R_SHIN_R_SHIN_001_POSE_8-24-20_Default_OBJ_073_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_073']} />
          <mesh geometry={nodes['R_SHIN_R_SHIN_001_POSE_8-24-20_Default_OBJ_073_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_073']} />
          <mesh geometry={nodes['R_SHIN_R_SHIN_001_POSE_8-24-20_Default_OBJ_073_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_073']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['TORSO_POSE_8-24-20_Default_OBJ_074_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_074']} />
          <mesh geometry={nodes['TORSO_POSE_8-24-20_Default_OBJ_074_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_074']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['WING_POSE_8-24-20_Default_OBJ_075_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_075']} />
          <mesh geometry={nodes['WING_POSE_8-24-20_Default_OBJ_075_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_075']} />
          <mesh geometry={nodes['WING_POSE_8-24-20_Default_OBJ_075_0_2'].geometry} material={materials['POSE_8-24-20_Default_OBJ_075']} />
        </group>
        <group position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes['TORSO_LOWER_ARMOR_POSE_8-24-20_Default_OBJ_076_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_076']} />
          <mesh geometry={nodes['TORSO_LOWER_ARMOR_POSE_8-24-20_Default_OBJ_076_0_1'].geometry} material={materials['POSE_8-24-20_Default_OBJ_076']} />
        </group>
        <mesh geometry={nodes['L_ELBOW_MESH_POSE_8-24-20_Default_OBJ_002_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_002']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_HAND_INDEX_3_POSE_8-24-20_Default_OBJ_008_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_008']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_HAND_MIDDLE_3_POSE_8-24-20_Default_OBJ_011_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_011']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_HAND_PALM_ARMOR_POSE_8-24-20_Default_OBJ_012_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_012']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_HAND_PINKY_3_POSE_8-24-20_Default_OBJ_015_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_015']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_HAND_RING_3_POSE_8-24-20_Default_OBJ_018_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_018']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_KNEE_POSE_8-24-20_Default_OBJ_023_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_023']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_KNEE_MESH_POSE_8-24-20_Default_OBJ_024_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_024']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_SHOULDER_POSE_8-24-20_Default_OBJ_026_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_026']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_SHOULDER_MESH_POSE_8-24-20_Default_OBJ_027_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_027']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_THIGH_POSE_8-24-20_Default_OBJ_029_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_029']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_THIGH_MESH_POSE_8-24-20_Default_OBJ_030_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_030']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_ELBOW_MESH_POSE_8-24-20_Default_OBJ_032_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_032']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_HAND_INDEX_3_POSE_8-24-20_Default_OBJ_038_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_038']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_HAND_MIDDLE_3_POSE_8-24-20_Default_OBJ_041_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_041']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_HAND_PALM_ARMOR_POSE_8-24-20_Default_OBJ_042_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_042']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_HAND_PINKY_3_POSE_8-24-20_Default_OBJ_045_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_045']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_HAND_RING_3_POSE_8-24-20_Default_OBJ_048_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_048']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_KNEE_POSE_8-24-20_Default_OBJ_054_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_054']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_KNEE_MESH_POSE_8-24-20_Default_OBJ_055_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_055']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_SHOULDER_POSE_8-24-20_Default_OBJ_056_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_056']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_SHOUDLER_MESH_POSE_8-24-20_Default_OBJ_057_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_057']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_THIGH_POSE_8-24-20_Default_OBJ_059_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_059']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_THIGH_MESH_POSE_8-24-20_Default_OBJ_060_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_060']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['L_FOOT_TOP_PLATE_POSE_8-24-20_Default_OBJ_069_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_069']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes['R_FOOT_TOP_PLATE_POSE_8-24-20_Default_OBJ_072_0'].geometry} material={materials['POSE_8-24-20_Default_OBJ_072']} position={[-4.452, 0.619, 4.277]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
